# -*- coding: utf-8 -*-
"""Reprogrammed_ad.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M_q0Rq0nownxEMprxk_X6DESdTW16XN3
"""

import numpy as np

def adversarial_program(t, theta):
    # Input:
    # t: Sequence of tokens
    # theta: Embedding tensor

    # Output:
    # Reprogrammed image

    # Get the dimensions from the embedding tensor
    vt, p, _, c = theta.shape

    # Calculate the height and width of the output image
    h = int(np.sqrt(vt * p * p // c))
    w = c * h

    # Initialize the output image x
    x = np.zeros((h, w, c))

    # Reprogram the image based on the input sequence
    for k, tk in enumerate(t):
        i = (k * p) // (h * c)
        j = (k * p) % w
        x[i:i + p, j:j + p, :] = np.tanh(theta[tk, :, :, :])

    return x